<template>
  <div class="main-container">
    <h2>How Solar System Save Your Bill</h2>
    <div v-for="(item, index) in renderData" class="display-row">
      <div>
        <div class="box">{{ index+1 }}</div>
      </div>
      <div class="content-container">
        <h3>{{ item.title }}</h3>
        <p>{{ item.content }}</p>
      </div>
    </div>
  </div>
</template>
<script setup>
const renderData = [
  {
    title: 'Noon-Day Time period',
    content: 'During the daytime, when the sun is at its peak, your solar system generate a higher power than what you are consuming at that time. The applications in the house will prioritize using electricity generated by the solar system. The excess generation will be exported back to the grid, and you will receive solar credits based on how much is exported.( It will vary in NSW area for sun tax policy)'
  },{
    title: 'Early morning and late afternoon period',
    content: 'During this period, your house might have higher power consumption because the sun is not as strong. The solar system will supply all it generates to your side, and the rest of the demand will be met by purchasing power from the grid. If you have a battery system, it will be another energy backup system for you.'
  },{
    title: 'Night time period',
    content: 'Unless you have battery, all of electricty you used at night will be from grid. However, since you have solar credits gained during daytime period, your majority bill during night time will be coverd by solar credits if you install a big enough system.'
  },
]
</script>
<style scoped>
.main-container {
  text-align: left;
}
.display-row {
  display: flex;
  flex-direction: row;
}
h3 {
  margin-top: 0;
}
.box {
  color: #C7CDD6;
  background: #434348;
  font-size: 1.75rem;
  border-radius: 2px;
  width: 3rem;
  width: 3rem;
  text-align: center;
  margin-right: 1rem;
}
</style>