name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: build fnovatech
        run: npm install
      - name: build fnovatech
        run: npm run build
        
      - name: upload dist source to tencent cloud
